language: node_js

node_js:
  - "stable"
  - "12.0"
  - "10.0"
  - "9.0"
  - "8.0"
  - "7.0"
  - "6.0"
  - "5.0"
  - "4.0"

matrix:
  fast_finish: true
  include:
    - node_js: stable
      env: COMMAND=jest:cov
  allow_failures:
      - node_js: '5.0'
      - node_js: '4.0'


sudo: false

cache:
  directories:
    - node_modules

env:
  - COMMAND=test

# before_script:
#   - npm i -g npx

script:
  - npm run ${COMMAND:-"test"}

after_script:
  - npx codecov

deploy:
  provider: npm
  email: contact@duzun.me
  api_key:
    secure: UeTmKdjg0MEmy8iK0ZmlmNww+hytHQoEkh7uhssV2Pizq2sSEKki9m64v7xe35Kwk38TcbMvrZkwtim/ZnZt1JJ2LOw8Ogz88OVviqAfkHOe2VRH8SrP3NpRFGFWLZ0JmvKGkvCLiDkLHiz+vSegUXDPwyGdpS932lyxJ5U3ntE=
  on:
    tags: true
    repo: duzun/base64util
